description: mnist_pytorch_grid
data:
  url: https://s3-us-west-2.amazonaws.com/determined-ai-test-data/pytorch_mnist.tar.gz
hyperparameters:
  learning_rate: 1.0
  global_batch_size: 64
  n_filters1: 32
  n_filters2: 64
  dropout1: 0.25
  dropout2: 0.5
  split:
    type: categorical
    vals: [0,1,2,3]
  n_splits: 5
  random: 1337
searcher:
  name: grid
  metric: validation_loss
  smaller_is_better: true
  max_length:
    batches: 937 #60,000 training images with batch size 64
entrypoint: model_def:MNistTrial
max_restarts: 0