description: efficientdet_distributed_default_cycle
# environment:
#   image: aaron276h/pytorch-1.6
hyperparameters:
  global_batch_size: 88
  min_loss_scale: 16
  sync_bn: False
  model_ema: True
  root: '/mnt/data'
  dataset: coco
  model: efficientdet_d0 #tf_efficientdet_d1
  redundant_bias: None
  val_skip: 0
  num_classes: None
  pretrained: False
  no_pretrained_backbone: False

  model_ema_decay: 0.9999
  initial_checkpoint: None
  dist_bn: None
  output: None

  decay_rate: 0.1
  resume: ''
  no_resume_opt: False
  mean: None
  std: None
  interpolation: ''
  fill_color: None
  clip_grad: 10.0
  opt: fusedmomentum
  opt_eps: 0.001
  momentum: 0.9
  weight_decay: 4e-05
  sched: cosine
  lr: 0.12
  lr_noise: 0.4 0.9
  lr_noise_pct: 0.67
  lr_noise_std: 1.0
  lr_cycle_mul: 1.0
  lr_cycle_limit: 1
  warmup_lr: 0.0001
  min_lr: 1e-5
  epochs: 300
  start_epoch: None
  decay_epochs: 30
  warmup_epochs: 5
  cooldown_epochs: 10
  patience_epochs: 10
  color_jitter: 0.4
  aa: None
  reprob: 0.
  remode: pixel
  recount: 1
  train_interpolation: random
  smoothing: None
  jit_loss: None
  new_focal: None
  seed: 42
  recovery_interval: 0
  workers: 4
  save_images: False
  amp: True
  channels_last: False
  pin_mem: False
  no_prefetcher: False
  bench_labeler: False
  eval_metric: map
  tta: 0
# optimizations:
#    tensor_fusion_threshold: 1
#    tensor_fusion_cycle_time: 2
records_per_epoch: 118287
searcher:
  name: single
  metric: val_loss
  max_length:
      epochs: 300
  smaller_is_better: true
resources:
  slots_per_trial: 4
reproducibility:
  experiment_seed: 42
min_validation_period:
  epochs: 1
  # batches: 10
entrypoint: model_def:EffDetTrial
max_restarts: 0
bind_mounts:
  - host_path: /home/katie/projects/data/coco
    container_path: /mnt/data